### ISSUE TITLE
GemsEconomy plugin support

### ISSUE THREAD

**Issue by Thermors** [nulli0n/ExcellentShop-spigot#2]
GemsEconomy is a plugin that supports using multiple currencies.
Please, could you add the support for the GemsEconomy plugin? This is a page of the plugin:
https://www.spigotmc.org/resources/gemseconomy.19655/
It has not got a maintainer at the moment.
Also, could you add the support for its fork: 
https://www.spigotmc.org/resources/gemseconomy-remake-unofficial-fork-1-19-ready.95658/

**Comment by Akiranya** [comment]
I am also hoping the integrations with GemsEconomy!

It's a great multi currency plugin and it would be fantastic if ExcenllentShop could add the support! And I know that ExcellentShop iteself has the multi-currency feature but the problem is that it's difficulty (or impossible?) to integrate with existing multi-currency system of a server if there is already any (like GemsEconomy)... Hopefully this request could be considered

**Comment by Akiranya** [comment]
Implemented in #3. Enjoy it :)

**Comment by Thermors** [comment]
Thanks a million! I'm really happy!
That's nice present for Christmas!
